# Generated by Django 2.2 on 2021-07-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
